services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: izumu-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=IzumuPassword123